name: sync-upstream

on:
  schedule:
    - cron: "23 7 * * *"
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: sync-upstream

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add remotes and fetch
        run: |
          git remote add upstream https://github.com/parcel-bundler/lightningcss || true
          git fetch upstream --tags --prune
          git fetch origin --tags --prune

      - name: Record initial HEAD
        id: head
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Compute ahead/behind vs upstream/master
        id: ab
        run: |
          BASE=$(git merge-base HEAD upstream/master)
          BEHIND=$(git rev-list --left-only --count HEAD...upstream/master)
          AHEAD=$(git rev-list --right-only --count HEAD...upstream/master)
          echo "base=$BASE"     >> "$GITHUB_OUTPUT"
          echo "behind=$BEHIND" >> "$GITHUB_OUTPUT"
          echo "ahead=$AHEAD"   >> "$GITHUB_OUTPUT"

      - name: Merge upstream/master into master
        id: merge
        if: ${{ steps.ab.outputs.behind != '0' }}
        continue-on-error: true
        run: |
          git merge upstream/master -X ours --no-edit

      - name: Create PR for upstream changes
        if: ${{ failure() && steps.ab.outputs.behind != '0' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git merge --abort || true
          gh pr create \
            --title "Sync upstream lightningcss" \
            --body "Automatic upstream sync detected conflicts. Please review and merge manually." \
            --head upstream/master \
            --base master

      - name: Push branch and sync tags
        if: ${{ success() && steps.ab.outputs.behind != '0' }}
        run: |
          set -euo pipefail
          BRANCH_TIP=$(git rev-parse master)
          if [[ "${{ steps.head.outputs.sha }}" != "$BRANCH_TIP" ]]; then
            echo "Pushing branch master"
            git push origin master
          else
            echo "Branch unchanged; not pushing master"
          fi
          git push origin --tags

      - name: Create issue on push failure
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --title "Upstream sync workflow failed: push error" \
            --body "The automatic upstream sync failed while pushing. Check the workflow run for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
